### PR TITLE
Support for Dynamic Workspace Names using Workspace Numbers

### PR DESCRIPTION
**Pull request by develNor**
Hi Ryan,

I love your "i3-workspace-history" repo! I’ve made some changes to support dynamic workspace names, similar to those used in setups like [workstyle](https://github.com/pierrechevalier83/workstyle), where workspaces are renamed based on active applications. To handle this, I adapted the script to use workspace numbers instead of names, extracting the number from the name string. This approach keeps things consistent even with dynamic renaming.

Let me know if you'd be interested in these updates!

Best,
Develnor

### CODE REVIEW

**Comment by RyanGibb** [comment]
develNor ***@***.***> writes:
> Hi Ryan,
>
> I love your "i3-workspace-history" repo! I=E2=80=99ve made some changes t=
o support dynamic workspace names, similar to those used in setups like
> workstyle, where workspaces are renamed based on active applications. To =
handle this, I adapted the script to use workspace numbers instead
> of names, extracting the number from the name string. This approach keeps=
 things consistent even with dynamic renaming.
>
> Let me know if you'd be interested in these updates!
>
> Best,
> Develnor
>
> -------------------------------------------------------------------------=
------------------------------------------------
>
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/RyanGibb/i3-workspace-history/pull/2
>
> Commit Summary
>
> * 8ba83a0 use workspace number instead of full names
>
> File Changes=20
>
> (1 file)
>
> * M i3-workspace-history.go (53)=20
>
> Patch Links:
>
> * https://github.com/RyanGibb/i3-workspace-history/pull/2.patch
> * https://github.com/RyanGibb/i3-workspace-history/pull/2.diff
>
> =E2=80=94
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

--=20
Ryan Gibb

**Comment by RyanGibb** [comment]
Seems my email got mangled!

Hi Develnor!

Thanks for the kind words, and the PR :-)

I would be interested in merging this, but at the moment it doesn't handle
 the case where the workspace doesn't contain any number.

E.g. switching to a 'test' workspace:
> Failed to extract workspace number: strconv.Atoi: parsing "": invalid
 syntax

Perhaps we could use a number if it's there and otherwise use the string?
This wouldn't disinguish between workspaces with the same number but
different names, but I think that's fine; if someone cares about this in
the future we can hide this behind a feature flag.

Also, a small nit, it seems like the white space isn't consistent.

Best,
-- Ryan

**Comment by develNor** [comment]
Hi Ryan,

Thanks again for your feedback! I’ve updated the implementation based on your suggestions.
I only tested this for my setup where I always have the leading number. Let me know if these changes work for you, and I’d be happy to address any further comments.

Best,
Develnor

**Comment by RyanGibb** [comment]
Magic, this seems to address all my functionality concerns! I'll do a format for consistent whitespace. Thanks Develnor :-)

**Pull request merged**
